### ISSUE TITLE
Thank you for building this tool, the manufacturer's app is barely functional.

### ISSUE THREAD

**Issue by chowyuncat** [ceandre/radonreader#1]

**Comment by ceandre** [comment]
Thanks. Glad for help :)

**Comment by RamSet** [comment]
I subscribe to the above THANK YOU.

I am using this to automate Radon exhaust now.

Thank you.

**Comment by ceandre** [comment]
> I subscribe to the above THANK YOU.
> 
> I am using this to automate Radon exhaust now.
> 
> Thank you.

No problem :)

**Comment by lukaskotik** [comment]
Thanks for the code. Any hint how to get the data (in the app called "log") from the device through bluetooth?
