### ISSUE TITLE
Question on Setup

### ISSUE THREAD

**Issue by JudeLabs** [ceandre/radonreader#2]
I have been using your script for several months and then it stopped working.  It cannot find the RadonEye.  Do you have to pair the device first using bluetoothctl or does the script handle it all?

**Comment by dicer** [comment]
I had the same problem. I got connection failed all the time after getting hundreds of values using the v2 script. 
It was like this for several months now and I think it stopped working when I tried to connect from another computer using the same script. That never worked and my laptop couldn't connect either anymore.

The device is still working though and the official app can connect. Firmware seems to be 1.2.4. I played around with the app and downloaded the log. Not much else to do.

**I then retried to connect with my laptop and it works again!** I guess downloading the old data fixed something? Let's see for how long the script keeps working
