### ISSUE TITLE
Bluetooth Address?

### ISSUE THREAD

**Issue by apenngrace** [ceandre/radonreader#3]
How do you find the bluetooth address for the device?

**Comment by dan-cristian** [comment]
You can use a Bluetooth scanner mobile app from Play Store

**Comment by Hardy62wo** [comment]
I m get ing an error ...


sudo bluetoothctl
power on
scan on
[bluetooth]# power on 
Changing power on succeeded 
[DEL] 
Device D2:C4:80:1E:C7:CD FR:R20:SN0090 
[bluetooth]# scan on
Discovery started  
[CHG] Controller DC:A6:32:15:6D:BD Discovering: yes
NEW] Device D2:C4:80:1E:C7:CD FR:R20:SN0090         
[bluetooth]#

 ./radon_reader.py -a D2:C4:80:1E:C7:CD -b -v

Connecting...
Failed to connect to peripheral D2:C4:80:1E:C7:CD, addr type: random
Failed, trying again (1)...
Connecting...
Failed to connect to peripheral D2:C4:80:1E:C7:CD, addr type: random
Failed, trying again (2)...
Connecting...
Failed to connect to peripheral D2:C4:80:1E:C7:CD, addr type: random
Failed, trying again (3)...
Connecting...
Failed to connect to peripheral D2:C4:80:1E:C7:CD, addr type: random
Failed.


I have a Raspberry 4!

Please can you help me ? Do I habe to modify the parameter und in Youtube script?
