### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by rucknapucknavitz** [ceandre/radonreader#4]
Wondering if this works under Python3?

I'm getting the following error:

```
rpi4:radonreader:% python3 radon_reader.py -a FB:74:xx:yy:zz:aa -v
Connecting...
Writing...
string argument without an encoding
Failed, trying again (1)...
Connecting...
Failed to connect to peripheral FB:74:xx:yy:zz:aa, addr type: random
Failed, trying again (2)...
Connecting...
Failed to connect to peripheral FB:74:xx:yy:zz:aa, addr type: random
Failed, trying again (3)...
Connecting...
Failed to connect to peripheral FB:74:xx:yy:zz:aa, addr type: random
Failed.
```

The Bluetooth indicator on the device does turn on during this process. 

Any and all ideas appreciated. Thanks!

**Comment by rucknapucknavitz** [comment]
Python2 is required and fixed my issue. Works great now.

**Comment by juergen2345** [comment]
I changed the shebang to #!/usr/bin/env python3
and line 49 in radon_reader.py: 
RadonEyeWrite.write(bytes("\x50"))
to 
RadonEyeWrite.write(b"\x50")
and it works in python 3.
but i did not test the mqtt and argparser part because i didn´t need it (removed it)
maybe this can help
